spring:
  rocketmq:
    consumer:
      # 必须启动 才能启动者 默认是false
      enable: true
    producer:
      enable: false
      #消费者订阅信息
    consumer-subscribe-info-list:
      - topic: TEST_CUSTOMER_TOPIC_TAG_ONE
        tagType: tag
        expression: TEST_CUSTOMER_TAG_ONE
      - topic: TEST_CUSTOMER_TOPIC_TAG_TWO
        tagType: tag
        expression: TEST_CUSTOMER_TAG_ONE || TEST_CUSTOMER_TOPIC_TWO
      - topic: TEST_CUSTOMER_TOPIC_SQL_ONE
        tagType: sql92
        expression: a > 9 AND b == 0
      - topic: TEST_CUSTOMER_TOPIC_SQL_TWO
        tagType: sql92
        expression: a == 1 AND c < 100