spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: all_virtual_host_admin
#    username: admin
    password: root
    virtual-host: virtual_host_test
    requested-heartbeat: 30
    connection-timeout: 30000
    publisher-returns: true
    publisher-confirm-type: simple
    dynamic: true
    listener:
      direct:
        acknowledge-mode: auto
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms
        max-interval: 1000ms
        #逐步递增的倍数
        multiplier: 1.0
       #设置 Exchange 在将消息分发给队列时，如果Exchange没有绑定队列或者绑定队列路由键不一致时，怎么处理这条消息 是丢弃还是返还给生产者
      #mandatory: true
    cache:
      connection:
        mode: connection
        size: 10
      channel:
        size: 10
        checkout-timeout: 10
    ssl:
      enabled: false
