server:
  port: 18801
spring:
  profiles:
    active: local
logging:
  level:
    org:
      springframework:
        amqp: debug
    com:
      rabbitmq: debug
  file:
    path: D:/Files/logs/rabbit-producer.log
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'