spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: all_virtual_host_admin
    #    username: admin
    password: root
    virtual-host: virtual_host_test
    #    virtual-host: /
    requested-heartbeat: 30
    connection-timeout: 30000
    publisher-returns: true
    publisher-confirm-type: correlated
    dynamic: true
    listener:
      direct:
        acknowledge-mode: manual
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms
        max-interval: 1000ms
        #逐步递增的倍数
        multiplier: 1.0
        #设置 Exchange 在将消息分发给队列时，如果Exchange没有绑定队列或者绑定队列路由键不一致时，怎么处理这条消息 是丢弃还是返还给生产者
      mandatory: true
    cache:
      connection:
        #        默认是 channel
        mode: connection
        size: 10
      channel:
        size: 10
        checkout-timeout: 10
    ssl:
      enabled: false
  transaction:
    application:
      name: transactonal_producer_application
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      userName: transactional
      password: 123456
      virtualHost: transaction_virtual_host
      requestedHeartbeat: 30
      publisherReturns: true
      publisherConfirmType: correlated
      acknowledgeMode: manual
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms
        max-interval: 1000ms
        #逐步递增的倍数
        multiplier: 1.0
        #设置 Exchange 在将消息分发给队列时，如果Exchange没有绑定队列或者绑定队列路由键不一致时，怎么处理这条消息 是丢弃还是返还给生产者
      mandatory: true
      cache:
        connection:
          mode: channel
        channel:
          size: 10
          checkout-timeout: 10
