server:
  port: 18802
logging:
  level:
    org:
      springframework:
        retry: debug
        amqp: info
        transaction: debug
    com:
      rabbitmq: info
spring:
  profiles:
    active: local
  application:
    name: rabbit_consumer_one
