spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: all_virtual_host_admin
    password: root
    virtual-host: virtual_host_test
    requested-heartbeat: 10
    publisher-returns: true
    publisher-confirm-type: simple
    #设置多大是合理的？？？
    connection-timeout: 100
    cache:
      connection:
        #Cache mode 的默认值
        mode: channel
        # 该值当 Cache mode 是 Connection 才有用
        size: 10
      channel:
        #SessionSize
        size: 10
        #单位 ms
        checkout-timeout: 10000
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000
        max-interval: 10000
        #递增的倍数
        multiplier: 2
      mandatory: true
  transaction:
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      userName: transactional
      password: 123456
      virtualHost: transaction_virtual_host
      requestedHeartbeat: 10
      publisherReturns: true
      publisherConfirmType: simple
      connectionTimeout: 100
      prefetchCount: 1
      channelTransacted: true
      concurrentConsumer: 1
      maxConcurrentConsumer: 10
      cache:
        connection:
          mode: channel
        channel:
          size: 10
          checkout-timeout: 10000
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000
        max-interval: 10000
        #递增的倍数
        multiplier: 2
      mandatory: true